# Generated by Django 5.0.7 on 2024-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Book_Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='books/D')),
            ],
        ),
        migrations.CreateModel(
            name='D_Movie_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='posters/D')),
            ],
        ),
        migrations.CreateModel(
            name='D_Song_Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('singer', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='songs/D')),
            ],
        ),
    ]
