# Generated by Django 5.0.7 on 2024-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0002_d_book_recommend_d_movie_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('actors', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('singer', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
