# Generated by Django 5.0.7 on 2024-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0003_savedcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcontent',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
