# Generated by Django 5.0.7 on 2024-07-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0004_alter_savedcontent_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcontent',
            name='content_id',
        ),
    ]
